function [] = inich();




global inioption

f = figure;

%inioption = 1;

%====================================
% Graphics initialization

	set(gcf, ...
        'NumberTitle','off', ...
     	  'Position',[ 350   100   250   610],...
        'Name','Loading Options', ...
        'backingstore','off');

%====================================
labelColor = [.05,.40,.75];   

%====================================
% The classic button
    uicontrol( ...
        'Style','push', ...
        'Position',[5 550 240 50], ...
        'String','Classic', ...
        'Callback','inioption = 1;close;');
%====================================
% The vergence button
    uicontrol( ...
        'Style','push', ...
        'Position',[5 490 240 50], ...
        'String','Vergence Behavior', ...
        'Callback','inioption = 2;close;');
     
%====================================
% The vergence button
    uicontrol( ...
        'Style','push', ...
        'Position',[5 430 240 50], ...
        'String','Vergence Unit', ...
        'Callback','inioption = 3;close;');


%====================================
% The head fixed button
    uicontrol( ...
        'Style','push', ...
        'Position',[5 370 240 50], ...
        'String','Head fixed', ...
        'Callback','inioption = 4;close;');

%====================================
% The head free button
    uicontrol( ...
        'Style','push', ...
        'Position',[5 310 240 50], ...
        'String','Sinusoidal Pursuit', ...
        'Callback','inioption = 5;close;');
     
%====================================
% The head free table button
    uicontrol( ...
        'Style','push', ...
        'Position',[5 250 240 50], ...
        'String','Head Free Table', ...
        'Callback','inioption = 6;close;');
     
%====================================
% The Head Free with Both Eyes button
    uicontrol( ...
        'Style','push', ...
        'Position',[5 190 240 50], ...
        'String','Head Free with Both Eyes', ...
        'Callback','inioption = 7;close;');

%====================================
% The Cowboy Left MN button
    uicontrol( ...
        'Style','push', ...
        'Position',[5 130 240 50], ...
        'String','Cowboy LEFT MN', ...
        'Callback','inioption = 8;close;');

%====================================
% The Cowboy Right MN button
    uicontrol( ...
        'Style','push', ...
        'Position',[5 70 240 50], ...
        'String','Cowboy RIGHT MN', ...
        'Callback','inioption = 9;close;');
     
%====================================
% The Bullfrog Right MN button
    uicontrol( ...
        'Style','push', ...
        'Position',[5 10 240 50], ...
        'String','Bullfrog RIGHT MN ', ...
        'Callback','inioption = 10;close;');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%====================================%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

uiwait(f);



