function [variables] = SCH_maker(action);

%This is the new and improved stich maker
%
%NOTE: it can be used from within a sorter, for example, if the variables
%      "SCH_to_save", "SCH_buffer" and "kept_ns" are defined in the calling function
%
%PAS 2001

if nargin<1,
    action='start';
end;

NewFlag = 0;
AddFlag = 0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  THE DEFAULTS ARE DEFINED HERE  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

assignin('base','SCH_to_save',['fr ua ghpos gvpos hhpos hvpos pconj pverg vf tach htar vtar yator pitor roltor filetype M ns index Ts lat variablestobesaved;']);

assignin('base','SCH_buffer',[500]);

%IMPORTANT NOTE:
%           to add a vector such as fr and ghpos that needs to be cut, you will
%           also need to edit SCH_add and SCH_new


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%         END OF DEFAULTS         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%Define and initialize "kept_ns" in the workspace 
assignin('base','kept_ns',[]);

if strcmp(action,'start'),
    
    % figure
    vars = figure('name','segment choice window',...
        'Position',[643  ,  42  , 300  , 100],...
        'number','off',...
        'Color',[.05,.456,.7],...
        'menubar','none',...
        'nextplot','replace',...
        'resize','off');
    
    
    
    % back	
    back_button = uicontrol(...
        'Style','push', ...
        'Position', [20 50 45 45], ...
        'String','BACK',...
        'CallBack','decmx');
    
    
    % forward
    
    dont_button = uicontrol(...
        'Style','push', ...
        'Position', [80 50 45 45], ...
        'String','NEXT',...
        'CallBack','incmx');
    
    
    % keep
    
    keep_call = [ ...
            'kept_ns = [kept_ns ns]; ' ...
            'disp(kept_ns); ' ...	
            'incmx; '];
    
    keep_button = uicontrol(...
        'Style','push', ...
        'Position', [140 50 45 45], ...
        'String','KEEP',...
        'CallBack',keep_call);
    
    
    % edit segment
    
    edtseg_call = [ ...
            'figure(hdatadisplay);', ...
            'edtseg; ']; 
    
    keep_button = uicontrol(...
        'Style','push', ...
        'Position', [80 31 105 15], ...
        'String','Edit Segment',...
        'CallBack',edtseg_call);
    
    
    % edit segment number choices
    edt_call = [ ...
            'def{1,1} = int2str(kept_ns);', ...
            'Answer = inputdlg(''Enter the segment numbers:'',''Segment Choice Window'',[1],def);', ...
            'kept_ns = sort(str2num(Answer{1,1}));', ...
            'ns = kept_ns; replot;', ...
            'clear def Answer;'];
    
    edit_button = uicontrol(...
        'Style','push',...
        'String','Edit',...
        'Position',[210 50 80 20],...
        'Callback', edt_call);
    
    
    % review
    
    rev_call = [ ...
            'ns = kept_ns; ' ...
            'timebase=''stac''; ' ...
            'figure(hdatadisplay);', ...
            'replot; ' ...
            'end; '];	
    
    rev_button = uicontrol(...
        'Style','push',...
        'String','Review',...
        'Position',[210 75 80 20],...
        'Callback',rev_call);
    
    
    % start stitch
    
    
    save_button = uicontrol(...
        'Style','push',...
        'String','START STICH',...
        'Position',[80 2 95 25],...
        'Callback','sch_new');
    
    
    % add to stitch
    
    
    add_button = uicontrol(...
        'Style','push',...
        'String','ADD STICH',...
        'Position',[195 2 95 25],...
        'Callback','SCH_add');
    
    
    % quit
    
    close_call = [ ...
            'clear kept_ns ; ' ...
            'schflag = 0; ' ...
            'close(gcf); '];
    
    quit_button = uicontrol(...
        'Style','push',...
        'String','QUIT',...
        'Position',[20 2 50 25],...
        'Callback',close_call);
    
end






