%Allows user to create a model (max 4 inputs, 1 output) using a GUI
%
%NOTE: always pick input signal BEFORE its derivative or amplitude
%
%Inputs stored in "in1to4"; Outputs in "out1"
%Also stores user choices in "model"
%These variables can be checked in the workspace
%These choices are not saved automatically
%
%Will then call dodyn3.m for estimation
%               predgui.m for predictions
%               dynlatpick.m for dynamic latency
%               bootstrap.m for bootstrap analysis
%
%PAS, 2000

in1to4 = []; out1 = []; model = ['---';'---';'---';'---';'---'];
in1to4 = zeros(N,4);
out1 = zeros(N,1);

mode_flag = 0; %set to x to predict, and to 9999 to change initial parameters
plotflag = 1; %set to 0 to prevent plotting of model.

%set figure window
load dynatwo

h0 = figure('Color',[0.3 0.6 0.9], ...
    'Colormap',mat0, ...
    'FileName',[matlabroot '\lab\sur\dynamics\dynatwo.m'], ...
    'PaperPosition',[18 180 576 432], ...
    'PaperUnits','points', ...
    'Position', [155   321   707   183], ...
    'Tag','Fig2', ...
    'IntegerHandle','off', ...
    'Name','Dynamic Analysis: 2 Inputs', ...
    'Menubar','none', ...
    'ToolBar','none');

%'Position', [155   377   707   127], ...


%LABELS
h1 = uicontrol('Parent',h0, ...
    'String','Input #1', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[30.75 120.5 69.75 10.25], ...
    'Style','text', ...
    'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
    'String','Input #2', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[123.1875 120.5 69.75 10.25], ...
    'Style','text', ...
    'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
    'String','Output', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[214.5 120.5 69.75 10.25], ...
    'Style','text', ...
    'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
    'String','Input #1a', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[30.75 25.5 69.75 10.25], ...
    'Style','text', ...
    'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
    'String','Input #2a', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[123.1875 25.5 69.75 10.25], ...
    'Style','text', ...
    'Tag','StaticText1');


%Choices
% Hamed: for letting the changes affect your signal uncomment this and
% comment the next one.

% in1 = uicontrol('Parent',h0, ...
%     'String',['none|' makelist1(Plotlist,NoofDisplayed)], ...
%     'Callback','k = []; sig = []; k = get(in1, ''value''); ks = get(in1, ''string''); if (k == 1), in1to4(:,1) = 0; model(1,1:3) = ''---'';model(1,4:end)='' ''; else, lat_t = lat; lat = 0; sig = eval(Signaldefinitions(listfind((Plotlist(k-1,:)), Signals),:)); in1to4(1:length(sig),1) = sig; lat = lat_t; model(1,1:length(Plotlist(k-1,1:end))) = (Plotlist(k-1,1:end));; end; set(in2d, ''Value'', 0); set(in2a, ''Value'', 0);set(ig1, ''Value'', 0);', ...
%     'Units','points', ...
%     'ListboxTop',0, ...
%     'Position',[30 96.25 71.25 21], ...
%     'Style','popupmenu', ...
%     'Tag','PopupMenu1', ...
%     'Value',1);
in1 = uicontrol('Parent',h0, ...
    'String',['none|' makelist1(Plotlist,NoofDisplayed)], ...
    'Callback','k = []; sig = []; k = get(in1, ''value''); ks = get(in1, ''string''); if (k == 1), in1to4(:,1) = 0; model(1,1:3) = ''---'';model(1,4:end)='' ''; else, lat_t = lat; lat = 0; if (check_inst==1), sig = Data.(strtrim((ks(k,:)))); elseif (check_inst==0), sig = eval(Signaldefinitions(listfind((Plotlist(k-1,:)), Signals),:)); end;  in1to4(1:length(sig),1) = sig; lat = lat_t; model(1,1:length(Plotlist(k-1,1:end))) = (Plotlist(k-1,1:end));; end; set(in2d, ''Value'', 0); set(in2a, ''Value'', 0);set(ig1, ''Value'', 0);', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[30 96.25 71.25 21], ...
    'Style','popupmenu', ...
    'Tag','PopupMenu1', ...
    'Value',1);



in3 = uicontrol('Parent',h0, ...
    'String',['none|' makelist1(Plotlist,NoofDisplayed)], ...
    'Callback','l = []; sig = []; l = get(in3, ''value''); if (l == 1), in1to4(:,3) = 0; model(2,1:3) = ''---'';model(2,4:end)='' ''; else, lat_t = lat; lat = 0; sig = eval(Signaldefinitions(listfind((Plotlist(l-1,:)), Signals),:)); in1to4(1:length(sig),3) = sig; lat = lat_t; model(3,1:length(Plotlist(l-1,1:end))) = (Plotlist(l-1,1:end)); end; set(in4d, ''Value'', 0); set(in4a, ''Value'', 0);set(ig3, ''Value'', 0);', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[122.4375 96.25 71.25 21], ...
    'Style','popupmenu', ...
    'Tag','PopupMenu1', ...
    'Value',1);

outs = uicontrol('Parent',h0, ...
    'String',['none|' makelist1(Plotlist)], ...
    'Callback','m = []; sig = []; m = get(outs, ''value''); if (m == 1), out1(:,1) = 0; model(5,1:3) = ''---''; else, lat_t = lat; lat = 0; sig = eval(Signaldefinitions(listfind((Plotlist(m-1,:)), Signals),:)); out1(1:length(sig),1) = sig; lat = lat_t; model(5,1:length(Plotlist(m-1,1:end))) = (Plotlist(m-1,1:end)); if (~strcmp(strtrim(Plotlist(m-1,1:end)),''fr'')); mode_flag = 1234; end; end;set(ig5, ''Value'', 0);', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[213.75 96.25 71.25 21], ...
    'Style','popupmenu', ...
    'Tag','PopupMenu1', ...
    'Value',1);

%Derivatives
in2d = uicontrol('Parent',h0, ...
    'String','Derivative', ...
    'Callback','if (sum(in1to4(:,2)) == 0); in1to4(2:length(in1to4),2) = diff(in1to4(:,1))./0.001; model(2,1:3) = ''der'';model(2,4:end)='' ''; else; in1to4(1:length(in1to4),2) = 0; model(2,1:3) = ''---'';model(2,4:end)='' ''; end;', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[36.75 80 57.75 13.5], ...
    'Style','checkbox', ...
    'Tag','Checkbox1');
in4d = uicontrol('Parent',h0, ...
    'String','Derivative', ...
    'Callback','if (sum(in1to4(:,4)) == 0); in1to4(2:length(in1to4),4) = diff(in1to4(:,3))./0.001; model(4,1:3) = ''der'';model(4,4:end)='' ''; else; in1to4(1:length(in1to4),4) = 0; model(4,1:3) = ''---'';model(4,4:end)='' ''; end;', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[129.1875 80 57.75 13.5], ...
    'Style','checkbox', ...
    'Tag','Checkbox1');

%Amplitudes
in2a = uicontrol('Parent',h0, ...
    'String','Amplitude', ...
    'Callback','if (sum(in1to4(:,2)) == 0); for j = 1:size(M,1); in1to4(M(j,1):M(j,2),2) = in1to4(M(j,2)+lat,1) - in1to4(M(j,1)+lat,1); end; model(2,1:3) = ''amp'';model(2,4:end)='' ''; else; in1to4(1:length(in1to4),2) = 0; model(2,1:3) = ''---'';model(2,4:end)='' ''; end;', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[36.75 63 57.75 13.5], ...
    'Style','checkbox', ...
    'Tag','Checkbox1');
in4a = uicontrol('Parent',h0, ...
    'String','Amplitude', ...
    'Callback','if (sum(in1to4(:,4)) == 0); for j = 1:size(M,1); in1to4(M(j,1):M(j,2),4) = in1to4(M(j,2)+lat,3) - in1to4(M(j,1)+lat,3); end; model(4,1:3) = ''amp'';model(4,4:end)='' '';; else; in1to4(1:length(in1to4),4) = 0; model(4,1:3) = ''---'';model(4,4:end)='' ''; end;', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[129.1875 63 57.75 13.5], ...
    'Style','checkbox', ...
    'Tag','Checkbox1');

%Ignore
ig1 = uicontrol('Parent',h0, ...
    'String','Ignore Input', ...
    'Callback','if (sum(in1to4(:,1)) ~= 0); in1to4(1:length(in1to4),1) = 0; model(1,1:3) = ''---'';model(1,4:end)='' ''; else; k = []; sig = []; k = get(in1, ''value''); if (k == 1), in1to4(:,1) = 0; model(1,1:3) = ''---'';model(1,4:end)='' ''; else, lat_t = lat; lat = 0; sig = eval(Signaldefinitions(listfind((Plotlist(k-1,:)), Signals),:)); in1to4(1:length(sig),1) = sig; lat = lat_t; end; model(1,1:length(Plotlist(k-1,1:end))) = (Plotlist(k-1,1:end)); end;', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[36.75 46 57.75 13.5], ...
    'Style','checkbox', ...
    'Tag','Checkbox1');
ig3 = uicontrol('Parent',h0, ...
    'String','Ignore Input', ...
    'Callback','if (sum(in1to4(:,3)) ~= 0); in1to4(1:length(in1to4),3) = 0; model(3,1:3) = ''---'';model(3,4:end)='' ''; else; k = []; sig = []; k = get(in3, ''value''); if (k == 1), in1to4(:,3) = 0; model(3,1:3) = ''---'';model(3,4:end)='' ''; else, lat_t = lat; lat = 0; sig = eval(Signaldefinitions(listfind((Plotlist(k-1,:)), Signals),:)); in1to4(1:length(sig),3) = sig; lat = lat_t; end; model(3,1:length(Plotlist(k-1,1:end))) = (Plotlist(k-1,1:end)); end;', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[129.1875 46 57.75 13.5], ...
    'Style','checkbox', ...
    'Tag','Checkbox1');
ig5 = uicontrol('Parent',h0, ...
    'String','Ignore Bias', ...
    'Callback','if (out1(1) ~= 9999); out1(1) = 9999; model(5,1) = ''B''; else; out1(1) = 0; model(5,1) = '' ''; end;', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[220.25 46 57.75 13.5], ...
    'Style','checkbox', ...
    'Tag','Checkbox1');

%Initial conditions
%iniC = uicontrol('Parent',h0, ...
%    'String','Ini. Cond.', ...
%    'Callback','if (mode_flag == 0); mode_flag = 9999; else; mode_flag = 0; end;', ...
%    'Units','points', ...
%    'ListboxTop',0, ...
%    'Position',[220.25 63 57.75 13.5], ...
%    'Style','checkbox', ...
%    'Tag','Checkbox1');


%Alternate Choices
in1a = uicontrol('Parent',h0, ...
    'String',['none|' makelist1(Plotlist,NoofDisplayed)], ...
    'Callback','k = []; sig = []; k = get(in1a, ''value''); if (k == 1), in1to4(:,2) = 0; model(2,1:3) = ''---''; model(2,4:end) = '' ''; else, lat_t = lat; lat = 0; sig = eval(Signaldefinitions(listfind((Plotlist(k-1,:)), Signals),:)); in1to4(1:length(sig),2) = sig; lat = lat_t; model(2,1:length(Plotlist(k-1,1:end))) = (Plotlist(k-1,1:end)); end;', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[30 1 71.25 21], ...
    'Style','popupmenu', ...
    'Tag','PopupMenu1', ...
    'Value',1);

in3a = uicontrol('Parent',h0, ...
    'String',['none|' makelist1(Plotlist,NoofDisplayed)], ...
    'Callback','l = []; sig = []; l = get(in3a, ''value''); if (l == 1), in1to4(:,4) = 0; model(4,1:3) = ''---''; model(4,4:end) = '' ''; else, lat_t = lat; lat = 0; sig = eval(Signaldefinitions(listfind((Plotlist(l-1,:)), Signals),:)); in1to4(1:length(sig),4) = sig; lat = lat_t; model(4,1:length(Plotlist(l-1,1:end))) = (Plotlist(l-1,1:end)); end;', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[122.4375 1 71.25 21], ...
    'Style','popupmenu', ...
    'Tag','PopupMenu1', ...
    'Value',1);


%Proceed
h1 = uicontrol('Parent',h0, ...
    'String','Estimate', ...
    'Callback','clear ho h1 in1 in2 in3 in4 outs x se error_sim VAF BIC est Others; close; [x,se,error_sim,VAF,BIC,est,Others] = dodyn3(M,ns,lat,out1,in1to4,mode_flag); plotdyn_2', ...
    'Fontsize',15, ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[327.75 108.25 63 20], ...
    'BackgroundColor',[1 0.1 0.25], ...
    'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
    'String','Predict', ...
    'Callback','clear ho h1 in1 in2 in3 in4 outs; close; predgui;', ...
    'Fontsize',15, ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[327.75 85.25 63 20], ...
    'BackgroundColor',[1 1 0.2], ...
    'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
    'String','Get Latency', ...
    'Callback','clear ho h1 in1 in2 in3 in4 outs sig; close; colordef black; [x,se,error_sim,VAF,BIC,est,Others] = dynlatpick(M,ns,lat,out1,in1to4,mode_flag); colordef white; M=M+lat-Others.lat;lat=Others.lat; plotflag=1; plotdyn_2; clear filename_e out1 in1to4 model; ', ...
    'Fontsize',9, ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[327.75 60 63 14], ...
    'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
    'String','Diagnostic', ...
    'Callback','clear ho h1 in1 in2 in3 in4 outs sig; close; [DIAG] = diagnostic(M,ns,lat,out1,in1to4,model,mode_flag);', ...
    'Fontsize',9, ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[327.75 43 63 14], ...
    'Tag','Pushbutton1');

%h1 = uicontrol('Parent',h0, ...
%    'String','Test Ini. Cond.', ...
%    'Callback','clear ho h1 in1 in2 in3 in4 outs sig; close; inicheck; clear filename_e out1 in1to4 model; ', ...
%    'Fontsize',9, ...
%    'Units','points', ...
%    'ListboxTop',0, ...
%    'Position',[327.75 26 63 14], ...
%    'Tag','Pushbutton1');


%Bootstrap Stuff

h1 = uicontrol('Parent',h0, ...
    'String','', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[409.75 7 110 121.25], ...
    'BackgroundColor', [0.2 0.8 0.0], ...
    'Style','text', ...
    'Tag','StaticText1');

h1 = uicontrol('Parent',h0, ...
    'String','Bootstrap', ...
    'Callback','clear ho h1 in1 in2 in3 in4 outs sig filename_m; close; clc; if exist(''hdatadisplay''); set(hdatadisplay,''visible'',''on''); end; global abort_flag; [filename_m] = bootstrap(M,ns,lat,out1,in1to4,mode_flag,userdir,model,0); if exist(''hdatadisplay''); set(hdatadisplay,''visible'',''on''); end; clear out1 in1to4 model; ', ...
    'Fontsize',9, ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[438.75 105 53 14], ...
    'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
   'String','Resume', ...
   'Callback','clear ho h1 in1 in2 in3 in4 outs sig filename_m; close; clc; set(hdatadisplay,''visible'',''on''); global abort_flag; [filename_m] = bootstrap(M,ns,lat,out1,in1to4,mode_flag,userdir,model,1); set(hdatadisplay,''visible'',''on''); clear filename_e out1 in1to4 model; ', ...
   'Fontsize',8, ...
   'FontName','Times New Roman', ...
   'Units','points', ...
   'ListboxTop',0, ...
   'Position',[417.75 82 30 14], ...
   'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
    'String','Export', ...
    'Callback','clear ho h1 in1 in2 in3 in4 outs sig filename_m; close; if (mode_flag == 9999); mode_flag = [8888 getini([100 0 0 0 0])]; end; [fname,pname] = uiputfile(''*.mat'',''Enter Filename (*.MAT)''); filename_e = [pname fname ''.mat'']; userdir = pname;  save(filename_e,''M'',''ns'',''lat'',''out1'',''in1to4'',''userdir'',''model'',''mode_flag''); clear filename_e pname fname out1 in1to4 model; ', ...
    'Fontsize',8, ...
    'FontName','Times New Roman', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[451.75 82 30 14], ...
    'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
    'String','Import', ...
    'Callback','clear M ns lat out1 in1to4 userdir model; [fname,pname] = uigetfile(''*.mat'',''Enter Filename (*.MAT)''); filename_i = [pname fname]; load(filename_i); clear filename_i pname fname; ', ...
   'Fontsize',8, ...
   'FontName','Times New Roman', ...
   'Units','points', ...
   'ListboxTop',0, ...
   'Position',[485.75 82 30 14], ...
   'Tag','Pushbutton1');


h1 = uicontrol('Parent',h0, ...
    'String','Multi-Unit', ...
    'Callback','clear ho h1 in1 in2 in3 in4 outs sig filename_m; close; set(hdatadisplay,''visible'',''on''); global abort_flag; bs_multi(0); set(hdatadisplay,''visible'',''on''); clear filename_i out1 in1to4 model; ', ...
    'Foregroundcolor',[1 .2 0], ...
    'Fontsize',9, ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[438.75 48 53 14], ...
    'Tag','Pushbutton1');


h1 = uicontrol('Parent',h0, ...
    'String','Boot: lat', ...
    'Callback','clear ho h1 in1 in2 in3 in4 outs sig filename_m; close; clc; if exist(''hdatadisplay''); set(hdatadisplay,''visible'',''on''); end; global abort_flag; mode_flag = [mode_flag 5678]; [filename_m] = bootstrap(M,ns,lat,out1,in1to4,mode_flag,userdir,model,0); if exist(''hdatadisplay''); set(hdatadisplay,''visible'',''on''); end; clear out1 in1to4 model; ', ...
    'Foregroundcolor',[0 0 1], ...
    'Fontsize',9, ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[438.75 32 53 14], ...
    'Tag','Pushbutton1');


h1 = uicontrol('Parent',h0, ...
   'String','Resume', ...
   'Callback','clear ho h1 in1 in2 in3 in4 outs sig filename_m; close; set(hdatadisplay,''visible'',''on''); global abort_flag; bs_multi(1); set(hdatadisplay,''visible'',''on''); clear filename_i out1 in1to4 model; ', ...
   'Foregroundcolor',[1 .2 0], ...
   'Fontsize',8, ...
   'FontName','Times New Roman', ...
   'Units','points', ...
   'ListboxTop',0, ...
   'Position',[450.75 15 30 14], ...
   'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
    'String','Latency Range (ms):', ...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[208.75 80 81.25 13.5], ...
    'Style','text', ...
    'Tag','StaticText1');
    
lat_max=20;
lat_range_max = uicontrol('Parent', h0,...
    'String', lat_max,...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[253.75 63 35.25 13.5], ...
    'Style','edit', ...
    'Tag','latrange',...
    'Callback', 'lat_max = str2double(get(lat_range_max, ''String''));');   

lat_min=0;
lat_range_min = uicontrol('Parent', h0,...
    'String', lat_min,...
    'Units','points', ...
    'ListboxTop',0, ...
    'Position',[208.75 63 35.25 13.5], ...
    'Style','edit', ...
    'Tag','latrange',...
    'Callback', 'lat_min = str2double(get(lat_range_min, ''String''));');  


