%

load choose_parzen

if exist('parzen_width') == 0,
   parzen_width = 10;  %set default
end;

h0 = figure('Color',[0.2 0.2 0.2], ...
	'Colormap',mat0, ...
	'FileName','C:\MATLAB\pacode\Fit Parzen\choose_parzen.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[405 496 205 106], ...
   'Tag','Fig2', ...
   'Number', 'off', ...
   'Name', 'Gaussian Width', ...
   'ToolBar','none');

question = uicontrol('Parent',h0, ...
   'String','Gaussian Width:', ...
   'Units','points', ...
	'ListboxTop',0, ...
	'Position',[8.25 46.5 40.5 20.25], ...
   'Style','text', ...
   'Tag','StaticText1');

answer = uicontrol('Parent',h0, ...
  	'Callback','get_it = get(answer,''String''); parzen_width = eval(get_it);', ...
   'String', num2str(parzen_width), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[63.75 43.5 79.5 13.25], ...
	'Style','edit', ...
	'Tag','EditText1');

go = uicontrol('Parent',h0, ...
   'Callback', 'close; [fr] = make_parzen(fr,ua,parzen_width); replot;', ...
   'String', 'Replot', ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[49.5 9 52.5 21], ...
	'Tag','Pushbutton1');
