paths:
  data_root: "Y:/Current Project Databases - NHP/2025 Cerebellum prosthesis"
  # location: "Nike/20260116_NRR_RW012"
  # session: "NRR_RW012"
  location: "Nike/20260226_NRR_RW019"
  session: "NRR_RW019"
  # location: "Nike/20260202_NRR_RW015"
  # session: "NRR_RW015"
  geom_mat_rel: "config/ImecPrimateStimRec128_BT_corrected_091525.mat"
  
kinematics:
  keypoints: [index, middle, hand, wrist, start, TA, TB]
  num_camera: 2

preprocessing:
  has_BR: True
  has_kinematics: True
  has_VOG: False
  has_HR: False
  output_aligned_mat: True
  process_only: [1, 2, 3] # Input as BR indexes, e.g. [1, 2] to only process BR_001 and BR_002

# ---- Spike preprocessing ----
highpass_hz: 300.0

probes:
  UA: 
    n_channels: 256
    mapping_mat_rel: "config/1106-22, 24, 42, 44 SN 11386-024040.xlsm"
    VOG_sig_ch: 131
    camera_sync_ch: 134
    triangle_sync_ch: 138
    VOG_sync_ch: 135
    HR_ch: 136
    touchscreen_ch: 142
    # geom_mat_rel: ""   # (optional) if you want a specific one for UA

  NN_DBS:
    local_radius_inner: 40 # Placeholder
    local_radius_outer: 120 # Placeholder
    n_channels: 32
    stim_channels: [1,2,3,4,5,6,7,8,9,10,11,12,21,22,23,24,25,26,27,28,29,30,31,32]
    rec_channels: [13,14,15,16,17,18,19,20]

  NPRW:
    local_radius_inner: 30
    local_radius_outer: 150
    n_channels: 128
    br_template_sync_ch: 0 # MAKE SURE THESE CHANNELS ARE CORRECT
    triangle_sync_ch: 1 # MAKE SURE THESE CHANNELS ARE CORRECT
    mapping_mat_rel: "config/ImecPrimateStimRec128_BT_corrected_091525.mat"
    neural_data_stream: "RHS2000 amplifier channel"
    stim_data_stream: "Stim channel"
    aux_stream: "USB board ADC input channel"
    ir_stream: "USB board digital input channel"

# ---- chunking / parallel ----
parallel_jobs: 2
threads_per_worker: 1
chunk: "4s"

# ---- Intan firing rate (threshold MUA) ----
NPRW_rate_est:
  bin_ms: 20.0          # bin width for counts
  sigma_ms: 20.0       # Gaussian kernel std
  detect_threshold: 3
  peak_sign: "neg"
  remove_ms_before: 20.0
  remove_tail_ms_after: 20.0
  dedup_ms: 0.25

# ---- BR firing rate (threshold MUA) ----
UA_rate_est:
  bin_ms: 20.0          # bin width for counts
  sigma_ms: 20.0       # Gaussian kernel std
  detect_threshold: 3
  peak_sign: "neg"
  remove_ms_before: 5.0
  remove_tail_ms_after: 5.0
  dedup_ms: 0.25

# ---- per-session overrides
sessions:
  BL_RW_003_Session_1:
    probe: "NPRW" # Placeholder
