import json
import argparse
import numpy as np
from pathlib import Path
import collections

"""
Script: analyze_stim_conditions.py

Description:
    Reads a JSON file of stimulation conditions (generated by generate_random_stim_conditions.py)
    and computes statistics on the selected channels to verify randomness and coverage.

Usage:
    python analyze_stim_conditions.py --input ./config/test_sample.json (--plot)
"""

def parse_channel_string(chan_str):
    """
    Parses "1-2 5 10-12" into [1, 2, 5, 10, 11, 12]
    """
    channels = []
    if not chan_str.strip():
        return channels
        
    parts = chan_str.strip().split()
    for part in parts:
        if '-' in part:
            try:
                start, end = map(int, part.split('-'))
                channels.extend(range(start, end + 1))
            except ValueError:
                print(f"Warning: Could not parse range '{part}'")
        else:
            try:
                channels.append(int(part))
            except ValueError:
                print(f"Warning: Could not parse number '{part}'")
    return channels

def main():
    parser = argparse.ArgumentParser(description="Analyze stimulation condition statistics.")
    parser.add_argument("--input", type=str, required=True, help="Input JSON file path")
    parser.add_argument("--plot", action="store_true", help="Generate distribution plots (PNG)")
    
    args = parser.parse_args()
    
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: File {input_path} not found.")
        return
        
    try:
        with open(input_path, "r") as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error loading JSON: {e}")
        return
        
    print(f"Loaded {len(data)} conditions from {input_path.name}")
    
    all_channels = []
    condition_stats = []
    
    for cond_id, val_str in data.items():
        # Format: "CATHODIC; ANODIC"
        # We process both or just CATHODIC? User usually puts everything in Cathodic.
        # Let's combine them for stats.
        
        parts = val_str.split(';')
        cathodic_str = parts[0]
        anodic_str = parts[1] if len(parts) > 1 else ""
        
        cathodes = parse_channel_string(cathodic_str)
        anodes = parse_channel_string(anodic_str)
        
        cond_channels = cathodes + anodes
        all_channels.extend(cond_channels)
        
        # Per-condition basic stats
        if cond_channels:
            condition_stats.append({
                "id": cond_id,
                "count": len(cond_channels),
                "min": np.min(cond_channels),
                "max": np.max(cond_channels),
                "mean": np.mean(cond_channels)
            })
            
    if not all_channels:
        print("No channels found in any condition.")
        return

    # Convert to numpy for stats
    all_channels_arr = np.array(all_channels)
    
    print("\n" + "="*40)
    print(" GLOBAL CHANNEL STATISTICS")
    print("="*40)
    print(f"Total Channel Selections: {len(all_channels)}")
    print(f"Unique Channels Used:     {len(np.unique(all_channels_arr))}")
    print(f"Min Channel Index:        {np.min(all_channels_arr)}")
    print(f"Max Channel Index:        {np.max(all_channels_arr)}")
    print(f"Mean Channel Index:       {np.mean(all_channels_arr):.2f}")
    print(f"Median Channel Index:     {np.median(all_channels_arr):.2f}")
    print(f"Std Dev:                  {np.std(all_channels_arr):.2f}")
    
    # Frequency analysis
    counts = collections.Counter(all_channels)
    freqs = list(counts.values())
    
    print("\n" + "="*40)
    print(" USAGE DISTRIBUTION")
    print("="*40)
    print(f"Most Frequent Channel:    {counts.most_common(1)[0][0]} ({counts.most_common(1)[0][1]} times)")
    print(f"Least Frequent Channel:   {counts.most_common()[-1][0]} ({counts.most_common()[-1][1]} times)")
    print(f"Mean Usage Count:         {np.mean(freqs):.2f}")
    print(f"Std Dev Usage Count:      {np.std(freqs):.2f}")
    
    # Check for missing channels (1-128)
    expected = set(range(1, 129))
    used = set(all_channels)
    missing = sorted(list(expected - used))
    
    if missing:
        print(f"\nWARNING: The following channels were NEVER selected: {missing}")
    else:
        print("\nSUCCESS: All 128 channels were selected at least once.")

    # --- Plotting ---
    if args.plot:
        try:
            import matplotlib.pyplot as plt
            import matplotlib.gridspec as gridspec
        except ImportError:
            print("Error: matplotlib is required for plotting.")
            return

        # Calculate Row Stats (Channels 1,2 -> Row 1)
        # Since selection is by row, ch1 count should equal ch2 count.
        # Row index 1-64.
        row_counts = collections.defaultdict(int)
        for ch in all_channels:
            row_idx = (ch + 1) // 2
            row_counts[row_idx] += 1
            
        row_x = np.arange(1, 65)
        row_y = []
        for r in row_x:
            c1 = 2*r - 1
            c2 = 2*r
            total = counts.get(c1, 0) + counts.get(c2, 0)
            row_y.append(total / 2.0) # Should be integer if strictly paired
            
        fig = plt.figure(figsize=(18, 12))
        gs = gridspec.GridSpec(2, 2, width_ratios=[3, 1], height_ratios=[4, 1])

        # 1. Bar Chart (Row Frequency)
        ax_bar = plt.subplot(gs[0, 0])
        ax_bar.bar(row_x, row_y, width=0.8, color='skyblue', edgecolor='black')
        ax_bar.set_xlim(0, 65)
        ax_bar.set_xlabel("Row Index (1-64)")
        ax_bar.set_ylabel("Selection Count")
        ax_bar.set_title(f"Row Selection Frequency (Total Row Selections: {len(all_channels)//2})")
        ax_bar.grid(axis='y', linestyle='--', alpha=0.7)

        # 2. Heatmap (Row Layout - 1D vertical strip)
        # 64 rows, 1 column
        heatmap_data = np.array(row_y).reshape(64, 1)

        ax_heat = plt.subplot(gs[0, 1])
        im = ax_heat.imshow(heatmap_data, cmap='viridis', aspect='auto', origin='upper')
        ax_heat.set_title("Row Density")
        ax_heat.set_ylabel("Row (1-64)")
        ax_heat.set_xticks([])
        
        # Colorbar
        cbar = plt.colorbar(im, ax=ax_heat)
        cbar.set_label("Count")

        # 3. Stats Text Box
        ax_text = plt.subplot(gs[1, :])
        ax_text.axis('off')
        
        stats_str = (
            f"GLOBAL STATS:\n"
            f"  Total Channel Selections: {len(all_channels)}\n"
            f"  Unique Channels: {len(np.unique(all_channels_arr))} / 128\n"
            f"\n"
            f"ROW STATS (1-64):\n"
            f"  Mean Selection:   {np.mean(row_y):.2f}\n"
            f"  Std Dev:          {np.std(row_y):.2f}\n"
            f"  Most Freq Row:    {row_x[np.argmax(row_y)]} ({np.max(row_y):.0f})\n"
            f"  Least Freq Row:   {row_x[np.argmin(row_y)]} ({np.min(row_y):.0f})"
        )
        
        ax_text.text(0.5, 0.5, stats_str, ha='center', va='center', 
                     fontsize=12, family='monospace', 
                     bbox=dict(boxstyle="round,pad=0.5", fc="white", ec="gray", alpha=0.9))

        plt.tight_layout()
        
        out_plot_path = input_path.with_suffix('.png')
        plt.savefig(out_plot_path)
        print(f"\nSaved distribution plot to: {out_plot_path}")

if __name__ == "__main__":
    main()
