function [] = filter_gui(action);

global F_Data F_Signals 

if nargin < 1,
   action='start';
end;

if strcmp(action,'start'),
   
   %             cutoff  slope
   F_Data     = [3    101    0    0];  
%    %            FR ehv hhv ghv ehp hhp ghp hvv gvv hvp gvp htar vtar vcj pcj vvg pvg 
%    F_Signals  = [0  0   0   0   0   0   0   0   0   0   0   0    0    0   0   0   0   ];
%            FR ehv hhv ghv ehp hhp ghp hvv gvv hvp gvp htar vtar vcj pcj
%            vvg pvg trx try trz
   F_Signals  = [0  0   0   0   0   0   0   0   0   0   0   0    0    0   0   0   0   0   0   0];
   %
   
   load filter_gui1
   
   h0 = figure('Color',[0.2 0.2 0.2], ...
      'Colormap',mat0, ...
      'FileName','C:\MATLAB\pacode\Other\filter_gui1.m', ...
      'PaperPosition',[18 180 576 432], ...
      'PaperUnits','points', ...
      'Position',[606 116 310 547], ...
      'Number','off', ...
      'Name','Filter GUI', ...
      'Tag','Fig2', ...
      'ToolBar','none');
   
   
   %%%%%%%%%%%%% SIGNALS TO FILTER
   
%    h1 = uicontrol('Parent',h0, ...
%       'String','FR34', ...
%       'Callback', 'filter_gui(''fr'')', ...
%       'Units','points', ...
%       'ListboxTop',0, ...
%       'Position',[12.75 375.75 58.5 19.5], ...
%       'Style','checkbox', ...
%       'Tag','Checkbox1');
   
   h1 = uicontrol('Parent',h0, ...
      'String','EHV', ...
      'Callback', 'filter_gui_AK(''ehv'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[12.75 343.5 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   h1 = uicontrol('Parent',h0, ...
      'String','HHV', ...
      'Callback', 'filter_gui_AK(''hhv'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[87 344.25 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   h1 = uicontrol('Parent',h0, ...
      'String','GHV', ...
      'Callback', 'filter_gui_AK(''ghv'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[160.5 344.25 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   
   h1 = uicontrol('Parent',h0, ...
      'String','EHP', ...
      'Callback', 'filter_gui_AK(''ehp'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[12.75 312 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   h1 = uicontrol('Parent',h0, ...
      'String','HHP', ...
      'Callback', 'filter_gui_AK(''hhp'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[86.25 312 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   h1 = uicontrol('Parent',h0, ...
      'String','GHP', ...
      'Callback', 'filter_gui_AK(''ghp'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[159.75 312 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   
   h1 = uicontrol('Parent',h0, ...
      'String','HVV', ...  
      'Callback', 'filter_gui_AK(''hvv'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[12.75 279.75 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   h1 = uicontrol('Parent',h0, ...
      'String','GVV', ...
      'Callback', 'filter_gui_AK(''gvv'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[86.25 280.5 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   
   h1 = uicontrol('Parent',h0, ...
      'String','HVP', ...
      'Callback', 'filter_gui_AK(''hvp'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[12.75 248.25 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   h1 = uicontrol('Parent',h0, ...
      'String','GVP', ...
      'Callback', 'filter_gui_AK(''gvp'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[86.25 248.25 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
  
   h1 = uicontrol('Parent',h0, ...
      'String','FR34', ...
      'Callback', 'filter_gui_AK(''fr'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[159.75 280.5 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
  
%%% accelerometer  
    h1 = uicontrol('Parent',h0, ...
      'String','xtrans', ...
      'Callback', 'filter_gui_AK(''trx'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[12.75 375.75 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
  
      h1 = uicontrol('Parent',h0, ...
      'String','ytrans', ...
      'Callback', 'filter_gui_AK(''try'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[86.25 375.75 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
  
      h1 = uicontrol('Parent',h0, ...
      'String','ztrans', ...
      'Callback', 'filter_gui_AK(''trz'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[159.75 375.75 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
%%%%%% frequency %AK modified
   h1 = uicontrol('Parent',h0, ...
      'String' , '0.5Hz', ...
      'Callback', 'filter_gui_AK(''0_5Hz'')', ...
      'Fontsize',16, ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[12.75 216 58.5 19.5], ...
      'Tag','Pushbutton1');
  h1 = uicontrol('Parent',h0, ...
      'String' , '1Hz', ...
      'Callback', 'filter_gui_AK(''1Hz'')', ...
      'Fontsize',16, ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[86.25 216.75 58.5 19.5], ...
      'Tag','Pushbutton1');
  
   h1 = uicontrol('Parent',h0, ...
      'String' , '2Hz', ...
      'Callback', 'filter_gui_AK(''2Hz'')', ...
      'Fontsize',16, ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[160.5 216.75 58.5 19.5], ...
      'Tag','Pushbutton1');
  
  h1 = uicontrol('Parent',h0, ...
      'String' , '4Hz', ...
      'Callback', 'filter_gui_AK(''4Hz'')', ...
      'Fontsize',16, ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[12.75 184.5 58.5 19.5], ...
      'Tag','Pushbutton1');
  
  h1 = uicontrol('Parent',h0, ...
      'String' , '8Hz', ...
      'Callback', 'filter_gui_AK(''8Hz'')', ...
      'Fontsize',16, ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[86.25 184.5 58.5 19.5], ...
      'Tag','Pushbutton1');
  
  
  h1 = uicontrol('Parent',h0, ...
      'String' , '10Hz', ...
      'Callback', 'filter_gui_AK(''10Hz'')', ...
      'Fontsize',16, ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[160.5 184.5 58.5 19.5], ...
      'Tag','Pushbutton1');
  
  h1 = uicontrol('Parent',h0, ...
      'String' , '12Hz', ...
      'Callback', 'filter_gui_AK(''12Hz'')', ...
      'Fontsize',16, ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[12.75 152.25 58.5 19.5], ...
      'Tag','Pushbutton1');
  
  h1 = uicontrol('Parent',h0, ...
      'String' , '16Hz', ...
      'Callback', 'filter_gui_AK(''16Hz'')', ...
      'Fontsize',16, ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[86.25 153 58.5 19.5], ...
      'Tag','Pushbutton1');
%   
%   h1 = uicontrol('Parent',h0, ...
%       'String' , '16Hz', ...
%       'Callback', 'filter_gui_AK(''16Hz'')', ...
%       'Fontsize',16, ...
%       'Units','points', ...
%       'ListboxTop',0, ...
%       'Position',[86.25 153 58.5 19.5], ...
%       'Tag','Pushbutton1');
  
  %{
   h1 = uicontrol('Parent',h0, ...
      'String','HTAR', ...
      'Callback', 'filter_gui(''htar'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[12.75 216 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   h1 = uicontrol('Parent',h0, ...
      'String','VTAR', ...
      'Callback', 'filter_gui(''vtar'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[86.25 216.75 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   
   h1 = uicontrol('Parent',h0, ...
      'String','VCJ', ...
      'Callback', 'filter_gui(''vcj'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[12.75 184.5 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   h1 = uicontrol('Parent',h0, ...
      'String','PCJ', ...
      'Callback', 'filter_gui(''pcj'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[86.25 184.5 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   
   h1 = uicontrol('Parent',h0, ...
      'String','VVG', ...
      'Callback', 'filter_gui(''vvg'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[12.75 152.25 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   h1 = uicontrol('Parent',h0, ...
      'String','PVG', ...
      'Callback', 'filter_gui(''pvg'')', ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[86.25 153 58.5 19.5], ...
      'Style','checkbox', ...
      'Tag','Checkbox1');
   %}
   %%%%%%%%%%%%%% FILTER SETTINGS
   
   h1 = uicontrol('Parent',h0, ...
      'String','FILTER CUT-OFF', ...
      'Units','points', ...
      'Fontsize',12, ...
      'ListboxTop',0, ...
      'Position',[12.75 108.75 90 21.75], ...
      'Style','text', ...
      'Tag','StaticText1');
   F_Data(3) = uicontrol('Parent',h0, ...
      'String', num2str(F_Data(1)), ...
      'Callback', 'filter_gui_AK(''set_cutoff'')', ...
      'Fontsize',14, ...
      'Units','points', ...
      'BackgroundColor',[1 1 1], ...
      'ListboxTop',0, ...
      'Position',[118.5 102.75 99.75 33.75], ...
      'Style','edit', ...
      'Tag','EditText1');
   
   h1 = uicontrol('Parent',h0, ...
      'String','FILTER ROLL_OFF', ...
      'Units','points', ...
      'Fontsize',12, ...
      'ListboxTop',0, ...
      'Position',[12.75 66 90 21.75], ...
      'Style','text', ...
      'Tag','StaticText1');
   F_Data(4) = uicontrol('Parent',h0, ...
      'String', num2str(F_Data(2)), ...
      'Callback', 'filter_gui_AK(''set_slope'')', ...
      'Units','points', ...
      'Fontsize',14, ...
      'BackgroundColor',[1 1 1], ...
      'ListboxTop',0, ...
      'Position',[118.5 62.25 99.75 33.75], ...
      'Style','edit', ...
      'Tag','EditText1');
   
   h1 = uicontrol('Parent',h0, ...
      'String' , 'FILTER', ...
      'Callback', 'close; filt_analysis;', ...
      'Fontsize',16, ...
      'Units','points', ...
      'ListboxTop',0, ...
      'Position',[75 4 81.75 24], ...
      'Tag','Pushbutton1');
   
   text(-0.04,0,'Note: the original signals will be overwritten!','color','green')
   axis off
   
   %%%%%%%%%%%%%%%%============================%%%%%%%%%%%%%%%%%%%%%%%%%==================
   
elseif strcmp(action,'fr'),
   F_Signals(1) = ~F_Signals(1);
elseif strcmp(action,'ehv'),
   F_Signals(2) = ~F_Signals(2);
elseif strcmp(action,'hhv'),
   F_Signals(3) = ~F_Signals(3);
elseif strcmp(action,'ghv'),
   F_Signals(4) = ~F_Signals(4);
elseif strcmp(action,'ehp'),
   F_Signals(5) = ~F_Signals(5);
elseif strcmp(action,'hhp'),
   F_Signals(6) = ~F_Signals(6);
elseif strcmp(action,'ghp'),
   F_Signals(7) = ~F_Signals(7);
elseif strcmp(action,'hvv'),
   F_Signals(8) = ~F_Signals(8);
elseif strcmp(action,'gvv'),
   F_Signals(9) = ~F_Signals(9);
elseif strcmp(action,'hvp'),
   F_Signals(10) = ~F_Signals(10);
elseif strcmp(action,'gvp'),
   F_Signals(11) = ~F_Signals(11);
elseif strcmp(action,'trx')
   F_Signals(18) = ~F_Signals(18);
elseif strcmp(action,'try'),
   F_Signals(19) = ~F_Signals(19);
elseif strcmp(action,'trz'),
   F_Signals(20) = ~F_Signals(20);
% frequency
elseif strcmp(action,'0_5Hz'),
   F_Data(1) = 3;
elseif strcmp(action,'1Hz'),
   F_Data(1) = 3;
elseif strcmp(action,'2Hz'),
   F_Data(1) = 5;
elseif strcmp(action,'4Hz'),
   F_Data(1) = 9;
elseif strcmp(action,'8Hz'),
   F_Data(1) = 17;
elseif strcmp(action,'10Hz'),
   F_Data(1) = 21;
elseif strcmp(action,'12Hz'),
   F_Data(1) = 25;
elseif strcmp(action,'16Hz'),
   F_Data(1) = 33;
%{
elseif strcmp(action,'htar'),
   F_Signals(12) = ~F_Signals(12);
elseif strcmp(action,'vtar'),
   F_Signals(13) = ~F_Signals(13);
elseif strcmp(action,'vcj'),
   F_Signals(14) = ~F_Signals(14);
elseif strcmp(action,'pcj'),
   F_Signals(15) = ~F_Signals(15);
elseif strcmp(action,'vvg'),
   F_Signals(16) = ~F_Signals(16);
elseif strcmp(action,'pvg'),
   F_Signals(17) = ~F_Signals(17);
%}  
   
elseif strcmp(action,'set_cutoff'),
   F_Data(1) = str2num(get(F_Data(3),'string'));
elseif strcmp(action,'set_slope'),
   F_Data(2) = str2num(get(F_Data(4),'string'));
   
  
end;
