%load predgui

x = [0 0 0 0 0];
n_imp = [(sum(in1to4(:,1)) ~= 0) (sum(in1to4(:,2)) ~= 0) (sum(in1to4(:,3)) ~= 0) (sum(in1to4(:,4)) ~= 0)];
str1 = ['Bias Value: '];
if n_imp(1) == 1; str2 = ['Gain for ',model(1,:),': ']; else; str2 = [' ']; end;
if n_imp(2) == 1; str3 = ['Gain for ',model(2,:),': ']; else; str3 = [' ']; end;
if n_imp(3) == 1; str4 = ['Gain for ',model(3,:),': ']; else; str4 = [' ']; end;
if n_imp(4) == 1; str5 = ['Gain for ',model(4,:),': ']; else; str5 = [' ']; end;



h0 = figure('Color',[1 0.5 0.2], ...
	'Colormap',mat0, ...
	'FileName','C:\MATLABR11\lab\sur\dynamics\predgui.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
   'Position',[324 265 373 305], ...
   'Name','Enter Parameters Here', ...
   'Tag','Fig3', ...
   'Menubar','none', ...
   'ToolBar','none');

%Labels
h1 = uicontrol('Parent',h0, ...
   'String', str1, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[13.5 183 144 21], ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
   'String', str2, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[13.5 155.25 144 21], ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
   'String', str3, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[13.5 127.5 144 21], ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
   'String', str4, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[13.5 99 144 21], ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
   'String', str5, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[13.5 71.25 144 21], ...
	'Style','text', ...
	'Tag','StaticText1');


%Entries
in1 = uicontrol('Parent',h0, ...
   'String', x(1), ...
  	'Callback','get_it = get(in1,''String'');x(1) = eval(get_it);', ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[174 182.25 92.25 22.5], ...
	'Style','edit', ...
	'Tag','EditText1');
in2 = uicontrol('Parent',h0, ...
   'String', x(2), ...
  	'Callback','get_it = get(in2,''String'');x(2) = eval(get_it);', ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[174 154.5 92.25 22.5], ...
	'Style','edit', ...
	'Tag','EditText1');
in3 = uicontrol('Parent',h0, ...
   'String', x(3), ...
  	'Callback','get_it = get(in3,''String'');x(3) = eval(get_it);', ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[174 126.75 92.25 22.5], ...
	'Style','edit', ...
	'Tag','EditText1');
in4 = uicontrol('Parent',h0, ...
   'String', x(4), ...
  	'Callback','get_it = get(in4,''String'');x(4) = eval(get_it);', ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[174 98.25 92.25 22.5], ...
	'Style','edit', ...
	'Tag','EditText1');
in5 = uicontrol('Parent',h0, ...
   'String', x(5), ...
  	'Callback','get_it = get(in5,''String'');x(5) = eval(get_it);', ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[174 70.5 92.25 22.5], ...
	'Style','edit', ...
	'Tag','EditText1');

%Predict
% the callback was changed to "dodyn_pred" instead of "dodyn3" so that the
% threshold (of 20) was not used for prediction.---------SSG------------
% (ONLY if want a full line for say a figure, if not then put "dodyn3")
h1 = uicontrol('Parent',h0, ...
   'Callback','clear ho h1 in1 in2 in3 in4 in5; close; [x,se,error_sim,VAF,BIC,est,Others] = dodyn3(M,ns,lat,out1,in1to4,x); plotdyn_2', ...
   'String', 'Predict', ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[100.5 18 87 31.5], ...
	'Tag','Pushbutton1');
